### ISSUE TITLE
Проект не собирается на последних версиях ноды

### ISSUE THREAD

**Issue by Baskins** [bem/sssr#10]
Речь про ветку по-умолчанию habrahabr
В моем случае current: {"node":"4.2.1","npm":"3.3.9"}
получаю ошибку

```
[baskin@MacBook-Pro /Volumes/data/www/bem/sssr-stable (habrahabr)]$ npm i

> sssr-tutorial@0.0.0 postinstall /Volumes/data/www/bem/sssr-stable
> bower-npm-install

(node) util.error is deprecated. Use console.error instead.
Error: Cannot find module 'bower/node_modules/bower-logger'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Volumes/data/www/bem/sssr-stable/node_modules/bower-npm-install/lib/install.js:9:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

npm WARN EPEERINVALID borschik-tech-cleancss@1.0.3 requires a peer of borschik@>=1.0.5 but none was installed.
npm WARN EPEERINVALID enb-autoprefixer@0.2.2 requires a peer of autoprefixer-core@~4.0.2 but none was installed.
npm WARN EPEERINVALID enb-borschik@1.5.0 requires a peer of borschik@^1.3.2 but none was installed.
npm WARN EPEERINVALID enb-borschik@1.5.0 requires a peer of enb-bembundle@^1.0.0 but none was installed.
npm WARN EPEERINVALID enb-modules@0.2.0 requires a peer of ym@~0.1.0 but none was installed.
npm WARN EPEERINVALID vow-queue@0.0.2 requires a peer of vow@~0.3.9 but none was installed.
npm WARN EPACKAGEJSON sssr-tutorial@0.0.0 No repository field.
npm WARN EPACKAGEJSON sssr-tutorial@0.0.0 No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/baskin/.nvm/versions/node/v4.2.1/bin/node" "/Users/baskin/.nvm/versions/node/v4.2.1/bin/npm" "i"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! sssr-tutorial@0.0.0 postinstall: `bower-npm-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sssr-tutorial@0.0.0 postinstall script 'bower-npm-install'.
npm ERR! This is most likely a problem with the sssr-tutorial package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower-npm-install
npm ERR! You can get their info via:
npm ERR!     npm owner ls sssr-tutorial
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/data/www/bem/sssr-stable/npm-debug.log
```

если переключится на старую версию ноды, до воссоединения с io.js, например на Node.js v0.12.7, в этом случае проект успешно собирается.

**Comment by tadatuta** [comment]
Спасибо за репорт!

Я обновил сборку в `master` и сделал его веткой по умолчанию. Теперь будет работать на свежей ноде.
